// 尾巴選物 — 商品資料(供商品詳情頁 product.html 與相關推薦共用)。
window.WEIBA_PRODUCTS = [
  { id:1, cat:"comfort", catLabel:"Comfort · 舒適寢具", badge:"New",
    cn:"天然羊毛窩墊", en:"Merino Wool Pet Blanket", price:"1,280", img:"images/wool-mat.webp",
    desc:"紐西蘭美麗諾羊毛，四季適用。天然抗菌、調溫，讓毛孩整年都舒適。",
    feats:["紐西蘭美麗諾羊毛，天然抗菌防螨","四季調溫，冬暖夏涼","可機洗、耐用不變形"] },
  { id:2, cat:"nutrition", catLabel:"Nutrition · 天然食品", badge:"有機",
    cn:"有機雞肉條", en:"Organic Chicken Strips", price:"380", img:"images/chicken.webp",
    desc:"台灣在地有機放牧雞，低溫烘乾。無防腐劑、無添加色素，毛孩最愛。",
    feats:["台灣在地有機放牧雞","低溫烘乾，鎖住營養與風味","無防腐劑、無人工色素"] },
  { id:3, cat:"lifestyle", catLabel:"Lifestyle · 生活風格", badge:"熱銷",
    cn:"植鞣革牽繩", en:"Vegetable-Tanned Leather Lead", price:"1,680", img:"images/leather-leash.webp",
    desc:"義大利植鞣牛皮，越用越有質感。黃銅五金，手縫收邊，職人工藝。",
    feats:["義大利植鞣牛皮，越用越有韻味","黃銅五金，堅固耐用","職人手縫收邊"] },
  { id:4, cat:"play", catLabel:"Play · 玩具益智",
    cn:"益智慢食玩具", en:"Slow Feeder Puzzle Toy", price:"560", img:"images/puzzle-toy.webp",
    desc:"獸醫師推薦設計，延緩進食速度，同時訓練狗狗嗅覺與大腦。食品級矽膠。",
    feats:["獸醫師推薦，延緩進食速度","訓練嗅覺與大腦，舒緩無聊","食品級矽膠，安全好清洗"] },
  { id:5, cat:"comfort", catLabel:"Comfort · 舒適寢具", badge:"熱銷",
    cn:"記憶棉圓形睡床", en:"Memory Foam Round Bed", price:"2,280", img:"images/bed.webp",
    desc:"NASA記憶棉材質，完美支撐毛孩關節。360度環抱設計，讓毛孩安心入睡。",
    feats:["NASA記憶棉，支撐關節減壓","360度環抱設計，安心包覆","防潑水內裡，外套可拆洗"] },
  { id:6, cat:"grooming", catLabel:"Grooming · 美容清潔",
    cn:"天然植萃沐浴露", en:"Natural Plant-Based Shampoo", price:"480", img:"images/shampoo.webp",
    desc:"燕麥+薰衣草配方，溫和潔淨不刺激敏感肌。適合各種毛色，沐浴後絲柔光澤。",
    feats:["燕麥+薰衣草，溫和不刺激","適合敏感肌與各種毛色","沐浴後絲柔光澤、淡雅清香"] },
  { id:7, cat:"nutrition", catLabel:"Nutrition · 天然食品", badge:"New",
    cn:"凍乾生食主食", en:"Freeze-Dried Raw Food", price:"890", img:"images/freeze-dried.webp",
    desc:"AAFCO完整營養標準，95%新鮮肉品。生食的好處，凍乾的便利。",
    feats:["95% 新鮮肉品，AAFCO 完整營養","凍乾保鮮，免冷凍好保存","加水還原，生食般的營養"] },
  { id:8, cat:"lifestyle", catLabel:"Lifestyle · 生活風格",
    cn:"藤編外出提籃", en:"Rattan Carrier Basket", price:"3,200", img:"images/carrier.webp",
    desc:"越南職人手工藤編，航空級強度。航空出行皆適用，時尚與機能兼備。",
    feats:["越南職人手工藤編，質感獨特","航空級強度，出行安心","通風透氣，毛孩舒適"] },
  { id:9, cat:"play", catLabel:"Play · 玩具益智",
    cn:"有機貓草玩具組", en:"Organic Catnip Toy Set", price:"420", img:"images/catnip.webp",
    desc:"日本有機貓草填充，手工縫製棉麻外套。四種造型，讓貓咪百玩不膩。",
    feats:["日本有機貓草，天然無添加","手工縫製棉麻外套，耐咬耐玩","四種造型，百玩不膩"] },
];
